#service.port=8080
spring.datasource.url=jdbc:mysql://localhost:3307/sys
spring.datesource.username=root
spring.datasource.password=sunxiaohou
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


canal.server=127.0.0.1:1111
canal.destination=example

#server.port=8081
